#!/home/matt/bin/php/bin/php
<?php

if ($argv[1] == 'stop') {
	$pid = file_get_contents('/home/matt/phergie/phergie.pid');
	posix_kill($pid, 9);
	sleep(1);
	exit(1);
}

$pid = pcntl_fork();
if ($pid == -1) {
	die('could not fork'); 
}
else if ($pid) {
	file_put_contents('/home/matt/phergie/phergie.pid', $pid);
	exit(0);
}

if (!posix_setsid()) {
  die('Could not detach from terminal.');
}

fclose(STDOUT);
fclose(STDIN);
fclose(STDERR);

chdir('/home/matt/phergie');
ob_start();
include "Bot.php";
ob_end_clean();
