<?php
/**
 */
class Phergie_Plugin_Yow extends Phergie_Plugin_Abstract_Command
{
    static public $yows = array(
	"I'm just waiting to be PICKED UP by some NUBILE TRUANTS!",
	'A dwarf is passing out somewhere in Detroit!',
        "Actually, what I'd like is a little toy spaceship!!",
        'All of life is a blur of Republicans and meat!',
        'Am I accompanied by a PARENT or GUARDIAN?',
        'Am I elected yet?',
        'Am I in GRADUATE SCHOOL yet?',
        'Am I SHOPLIFTING?',
        'An air of FRENCH FRIES permeates my nostrils!!',
        'An Italian is COMBING his hair in suburban DES MOINES!',
        'And furthermore, my bowling average is unimpeachable!!!',
        'Are the STEWED PRUNES still in the HAIR DRYER?',
        'Are we live or on tape?',
        'Are we on STRIKE yet?',
        'Are we THERE yet?',
        'Are we THERE yet?  My MIND is a SUBMARINE!!',
        'Are you mentally here at Pizza Hut??',
        'As President I have to go vacuum my coin collection!',
        'BARBARA STANWYCK makes me nervous!!',
        'BELA LUGOSI is my co-pilot ...',
        '... bleakness ... desolation ... plastic forks ...',
        'Bo Derek ruined my life!',
        "Boy, am I glad it's only 1971...",
        'But they went to MARS around 1953!!',
        'Can I have an IMPULSE ITEM instead?',
        'Can you MAIL a BEAN CAKE?',
        'Civilization is fun!  Anyway, it keeps me busy!!',
        'Could I have a drug overdose?',
        'Did I do an INCORRECT THING??',
        'Did I say I was a sardine?  Or a bus???',
        'Did I SELL OUT yet??',
        'Did YOU find a DIGITAL WATCH in YOUR box of VELVEETA?',
        'Did you move a lot of KOREAN STEAK KNIVES this trip, Dingy?',
        'DIDI ... is that a MARTIAN name, or, are we in ISRAEL?',
        "Didn't I buy a 1951 Packard from you last March in Cairo?",
        'Do I have a lifestyle yet?',
        'Do you guys know we just passed thru a BLACK HOLE in space?',
        'Do you like "TENDER VITTLES"?',
        'does your DRESSING ROOM have enough ASPARAGUS?',
        "Don't hit me!!  I'm in the Twilight Zone!!!",
        "Don't SANFORIZE me!!",
        'Edwin Meese made me wear CORDOVANS!!',
        'Eisenhower!!  Your mimeograph machine upsets my stomach!!',
        'Either CONFESS now or we go to "PEOPLE\'S COURT"!!',
        'Everybody gets free BORSCHT!',
        'Everywhere I look I see NEGATIVITY and ASPHALT ...',
        'FEELINGS are cascading over me!!!',
        'for ARTIFICIAL FLAVORING!!',
        "FUN is never having to say you're SUSHI!!",
        'Gibble, Gobble, we ACCEPT YOU ...',
        'Go on, EMOTE!  I was RAISED on thought balloons!!',
        'HAIR TONICS, please!!',
        'Half a mind is a terrible thing to waste!',
        'Has everybody got HALVAH spread all over their ANKLES??',
        '... he dominates the DECADENT SUBWAY SCENE.',
        "HELLO, everybody, I'm a HUMAN!!",
        "Hello, GORRY-O!!  I'm a GENIUS from HARVARD!!",
        'Here I am in 53 B.C. and all I want is a dill pickle!!',
        'Here we are in America ... when do we collect unemployment?',
        'Hold the MAYO & pass the COSMIC AWARENESS ...',
        'HOORAY, Ronald!!  Now YOU can marry LINDA RONSTADT too!!',
        'How do I get HOME?',
        "How's it going in those MODULAR LOVE UNITS??",
        "How's the wife?  Is she at home enjoying capitalism?",
        'HUGH BEAUMONT died in 1982!!',
        "I always have fun because I'm out of my mind!!!",
        'I am a jelly donut.  I am a jelly donut.',
        "I am having FUN...  I wonder if it's NET FUN or GROSS FUN?",
        'I am NOT a nut....',
        'I appoint you ambassador to Fantasy Island!!!',
        'I brought my BOWLING BALL -- and some DRUGS!!',
        "I can't decide which WRONG TURN to make first!!",
        'I demand IMPUNITY!',
        "... I don't like FRANK SINATRA or his CHILDREN.",
        "I don't understand the HUMOUR of the THREE STOOGES!!",
        'I feel ... JUGULAR ...',
        'I feel better about world problems now!',
        'I feel like a wet parking meter on Darvon!',
        'I feel partially hydrogenated!',
        "I had a lease on an OEDIPUS COMPLEX back in '81 ...",
        'I had pancake makeup for brunch!',
        'I have a TINY BOWL in my HEAD',
        'I have a very good DENTAL PLAN.  Thank you.',
        'I have accepted Provolone into my life!',
        'I have many CHARTS and DIAGRAMS..',
        '... I have read the INSTRUCTIONS ...',
        '-- I have seen the FUN --',
        'I have seen these EGG EXTENDERS in my Supermarket ...',
        'I hope I bought the right relish ... zzzzzzzzz ...',
        "I hope the ``Eurythmics'' practice birth control ...",
        'I invented skydiving in 1989!',
        'I joined scientology at a garage sale!!',
        'I just forgot my whole philosophy of life!!!',
        'I just had a NOSE JOB!!',
        'I just had my entire INTESTINAL TRACT coated with TEFLON!',
        'I just remembered something about a TOAD!',
        'I Know A Joke',
        'I know how to do SPECIAL EFFECTS!!',
        "I know th'MAMBO!!  I have a TWO-TONE CHEMISTRY SET!!",
        'I left my WALLET in the BATHROOM!!',
        'I like your SNOOPY POSTER!!',
        'I own seven-eighths of all the artists in downtown Burbank!',
        'I represent a sardine!!',
        'I request a weekend in Havana with Phil Silvers!',
        '... I see TOILET SEATS ...',
        'I smell a RANCID CORN DOG!',
        'I smell like a wet reducing clinic on Columbus Day!',
        'I think I am an overnight sensation right now!!',
        'I think my career is ruined!',
        '... I want a COLOR T.V. and a VIBRATING BED!!!',
        'I want a VEGETARIAN BURRITO to go ... with EXTRA MSG!!',
        'I want a WESSON OIL lease!!',
        'I want another RE-WRITE on my CEASAR SALAD!!',
        'I want to perform cranial activities with Tuesday Weld!!',
        'I want to so HAPPY, the VEINS in my neck STAND OUT!!',
        "I was making donuts and now I'm on a bus!",
        'I wonder if BOB GUCCIONE has these problems!',
        'I wonder if I could ever get started in the credit world?',
        'I wonder if I should put myself in ESCROW!!',
        "I wonder if there's anything GOOD on tonight?",
        'I would like to urinate in an OVULAR, porcelain pool --',
        "I'd like MY data-base JULIENNED and stir-fried!",
        "I'd like some JUNK FOOD ... and then I want to be ALONE --",
        "I'll eat ANYTHING that's BRIGHT BLUE!!",
        "I'll show you MY telex number if you show me YOURS ...",
        "I'm a fuschia bowling ball somewhere in Brittany",
        "I'm also against BODY-SURFING!!",
        "I'm also pre-POURED pre-MEDITATED and pre-RAPHAELITE!!",
        "I'm ANN LANDERS!!  I can SHOPLIFT!!",
        "I'm definitely not in Omaha!",
        "I'm EMOTIONAL now because I have MERCHANDISING CLOUT!!",
        "I'm encased in the lining of a pure pork sausage!!",
        "I'm GLAD I remembered to XEROX all my UNDERSHIRTS!!",
        "I'm having a BIG BANG THEORY!!",
        "I'm having a MID-WEEK CRISIS!",
        "I'm having an emotional outburst!!",
        "I'm having fun HITCHHIKING to CINCINNATI or FAR ROCKAWAY!!",
        "I'm in direct contact with many advanced fun CONCEPTS.",
        "I'm into SOFTWARE!",
        "I'm not an Iranian!!  I voted for Dianne Feinstein!!",
        "I'm not available for comment..",
        "I'm rated PG-34!!",
        "I'm receiving a coded message from EUBIE BLAKE!!",
        "I'm shaving!!  I'M SHAVING!!",
        "I'm wearing PAMPERS!!",
        "I'm wet!  I'm wild!",
        "I've got a COUSIN who works in the GARMENT DISTRICT ...",
        "I've read SEVEN MILLION books!!",
        'if it GLISTENS, gobble it!!',
        'If our behavior is strict, we do not need fun!',
        'In Newark the laundromats are open 24 hours a day!',
        "Inside, I'm already SOBBING!",
        'Is it clean in other dimensions?',
        'Is something VIOLENT going to happen to a GARBAGE CAN?',
        'Is this an out-take from the "BRADY BUNCH"?',
        'Is this going to involve RAW human ecstasy?',
        'Is this TERMINAL fun?',
        "Isn't this my STOP?!",
        "It don't mean a THING if you ain't got that SWING!!",
        'It\'s NO USE ... I\'ve gone to "CLUB MED"!!',
        "It's OKAY -- I'm an INTELLECTUAL, too.",
        'Jesuit priests are DATING CAREER DIPLOMATS!!',
        'Jesus is my POSTMASTER GENERAL ...',
        'LBJ, LBJ, how many JOKES did you tell today??!',
        'Let me do my TRIBUTE to FISHNET STOCKINGS ...',
        "Let's send the Russians defective lifestyle accessories!",
        "Life is a POPULARITY CONTEST!  I'm REFRESHINGLY CANDID!!",
        "Loni Anderson's hair should be LEGALIZED!!",
        'Look!  A ladder!  Maybe it leads to heaven, or a sandwich!',
        'Make me look like LINDA RONSTADT again!!',
        'Maybe we could paint GOLDIE HAWN a rich PRUSSIAN BLUE --',
        'MERYL STREEP is my obstetrician!',
        'MMM-MM!!  So THIS is BIO-NEBULATION! ',
        'My EARS are GONE!!',
        'My haircut is totally traditional!',
        'MY income is ALL disposable!',
        'My LESLIE GORE record is BROKEN ...',
        'My life is a patio of fun!',
        'My mind is a potato field ...',
        'My mind is making ashtrays in Dayton ...',
        'My nose feels like a bad Ronald Reagan movie ...',
        'my NOSE is NUMB!',
        'My vaseline is RUNNING...',
        'NANCY!!  Why is everything RED?!',
        'NEWARK has been REZONED!!  DES MOINES has been REZONED!!',
        'Nipples, dimples, knuckles, NICKLES, wrinkles, pimples!!',
        'Now I am depressed ...',
        'Now I understand the meaning of "THE MOD SQUAD"!',
        'Now that I have my "APPLE", I comprehend COST ACCOUNTING!!',
        '... Now, it\'s time to "HAVE A NAGEELA"!!',
        "Now, let's SEND OUT for QUICHE!!",
        'Oh my GOD -- the SUN just fell into YANKEE STADIUM!!',
        'Oh, I get it!!  "The BEACH goes on", huh, SONNY??',
        'One FISHWICH coming up!!',
        'over in west Philadelphia a puppy is vomiting ...',
        'PARDON me, am I speaking ENGLISH?',
        'PIZZA!!',
        'Please come home with me ... I have Tylenol!!',
        'Psychoanalysis??  I thought this was a nude rap session!!!',
        'PUNK ROCK!!  DISCO DUCK!!  BIRTH CONTROL!!',
        'Quick, sing me the BUDAPEST NATIONAL ANTHEM!!',
        'RELATIVES!!',
        'RHAPSODY in Glue!',
        'Should I do my BOBBIE VINTON medley?',
        'Sign my PETITION.',
        'So this is what it feels like to be potato salad',
        'TAILFINS!! ... click ...',
        "Th' MIND is the Pizza Palace of th' SOUL",
        "Thank god!! ... It's HENNY YOUNGMAN!!",
        'The Korean War must have been fun.',
        '... the MYSTERIANS are in here with my CORDUROY SOAP DISH!!',
        "There's enough money here to buy 5000 cans of Noodle-Roni!",
        'These PRESERVES should be FORCE-FED to PENTAGON OFFICIALS!!',
        "This is a NO-FRILLS flight -- hold th' CANADIAN BACON!!",
        "... this must be what it's like to be a COLLEGE GRADUATE!!",
        'This PIZZA symbolizes my COMPLETE EMOTIONAL RECOVERY!!',
        'This PORCUPINE knows his ZIPCODE ... And he has "VISA"!!',
        'TONY RANDALL!  Is YOUR life a PATIO of FUN??',
        'Uh-oh!!  I forgot to submit to COMPULSORY URINALYSIS!',
        "Uh-oh!!  I'm having TOO MUCH FUN!!",
        "UH-OH!!  We're out of AUTOMOBILE PARTS and RUBBER GOODS!",
        'Used staples are good with SOY SAUCE!',
        'VICARIOUSLY experience some reason to LIVE!!',
        "Was my SOY LOAF left out in th'RAIN?  It tastes REAL GOOD!!",
        'We have DIFFERENT amounts of HAIR --',
        'We just joined the civil hair patrol!',
        'Were these parsnips CORRECTLY MARINATED in TACO SAUCE?',
        'What GOOD is a CARDBOARD suitcase ANYWAY?',
        'What I need is a MATURE RELATIONSHIP with a FLOPPY DISK ...',
        'What PROGRAM are they watching?',
        'What UNIVERSE is this, please??',
        "What's the MATTER Sid? ... Is your BEVERAGE unsatisfactory?",
        "When this load is DONE I think I'll wash it AGAIN ...",
        "Where do your SOCKS go when you lose them in th' WASHER?",
        'Where does it go when you flush?',
        "Where's SANDY DUNCAN?",
        "Where's th' DAFFY DUCK EXHIBIT??",
        "Where's the Coke machine?  Tell me a joke!!",
        'WHO sees a BEACH BUNNY sobbing on a SHAG RUG?!',
        'Why are these athletic shoe salesmen following me??',
        'Why is everything made of Lycra Spandex?',
        'Will it improve my CASH FLOW?',
        'Will the third world war keep "Bosom Buddies" off the air?',
        "With YOU, I can be MYSELF ...  We don't NEED Dan Rather ...",
        'World War III?  No thanks!',
        "Wow!  Look!!  A stray meatball!!  Let's interview it!",
        'Xerox your lunch and file it under "sex offenders"!',
        "You can't hurt me!!  I have an ASSUMABLE MORTGAGE!!",
        "You mean you don't want to watch WRESTLING from ATLANTA?",
        "YOU PICKED KARL MALDEN'S NOSE!!",
        "You were s'posed to laugh!",
        'Yow!',
        'Yow!  Am I having fun yet?',
        'Yow!  Am I in Milwaukee?',
        'Yow!  Are we laid back yet?',
        'Yow!  Are we wet yet?',
        'Yow!  Are you the self-frying president?',
        'Yow!  I just went below the poverty line!',
        'Yow!  I threw up on my window!',
        'Yow!  I want my nose in lights!',
        'Yow!  I want to mail a bronzed artichoke to Nicaragua!',
        "Yow!  I'm imagining a surfer van filled with soy sauce!",
        'Yow!  Is my fallout shelter termite proof?',
        'Yow!  Is this sexual intercourse yet??  Is it, huh, is it??',
        "Yow!  It's a hole all the way to downtown Burbank!",
        'Yow!  Now we can become alcoholics!',
        "Yow!  We're going to a new disco!",
        'YOW!!  Everybody out of the GENETIC POOL!',
        "YOW!!  I'm in a very clever and adorable INSANE ASYLUM!!",
        'YOW!!  The land of the rising SONY!!',
        "YOW!!  Up ahead!  It's a DONUT HUT!!",
        'YOW!!!  I am having fun!!!',
        "Zippy's brain cells are straining to bridge synapses ...",
        "Yow!! I'm trying to break Zippy!!",
	"100,000 sperm and you were the fastest?",
	"42.7 percent of all statistics are made up on the spot.",
	"99 percent of lawyers give the rest a bad name.",
	"A bartender is just a pharmacist with a limited inventory.",
	"A clean desk is a sign of a cluttered desk drawer.",
	"A clear conscience is usually the sign of a bad memory.",
	"A closed mouth gathers no foot.",
	"A conclusion is the place where you got tired of thinking.",
	"A day without sunshine is like, night.",
	"A diplomat is someone who can tell you to go to hell in such a way that you will look forward to the trip.",
	"A flashlight is a case for holding dead batteries.",
	"All generalizations are false, including this one.",
	"All men are idiots, and I married their King.",
	"Always remember you're unique, just like everyone else.",
	"Always try to be modest and be proud of it!",
	"Anything worth taking seriously is worth making fun of.",
	"Artificial Intelligence usually beats real stupidity.",
	"Assassins do it from behind.",
	"Atheism is a non-prophet organization.",
	"Auntie Em, Hate you, hate Kansas, taking the dog. Dorothy.",
	"Be nice to your kids. They'll choose your nursing home.",
	"Beauty is in the eye of the beer holder.",
	"Beer: It's not just for breakfast anymore.",
	"Before you criticize someone, you should walk a mile in their shoes. That way, when you criticize them, you're a mile away and you have their shoes.",
	"Better to understand a little than to misunderstand a lot.",
	"Bills travel through the mail at twice the speed of checks",
	"Borrow money from a pessimist, they don't expect it back.",
	"Boycott shampoo! Demand the REAL poo!",
	"C program run. C program crash. C programmer quit.",
	"Change is inevitable, except from a vending machine.",
	"Chocolate: the OTHER major food group.",
	"Consciousness: That annoying time between naps.",
	"Corduroy pillows: They're making headlines!",
	"Could you drive any better if I shoved that cell phone up your ass?",
	"Criminal Lawyer is a redundancy.",
	"Daddy, why doesn't this magnet pick up this floppy disk?",
	"Death is hereditary.",
	"Despite the cost of living, have you noticed how popular it remains?",
	"Did anyone see my lost carrier?",
	"Diplomacy is the art of saying good doggie while looking for a bigger stick.",
	"Do not walk behind me, for I may not lead. Do not walk ahead of me, for I may not follow. Do not walk beside me, either. Just leave me alone.",
	"Don't be irreplaceable; if you can't be replaced, you can't be promoted.",
	"Don't drink and drive. You might hit a bump and spill your drink.",
	"Don't piss me off! I'm running out of places to hide the bodies.",
	"Don't take life too seriously, you won't get out alive.",
	"Double your drive space. Delete Windows!",
	"Duct tape is like the force, it has a light side and a dark side and it holds the universe together.",
	"Eagles may soar, but weasels don't get sucked into jet engines.",
	"Energizer Bunny arrested and charged with battery.",
	"Error, no keyboard. Press F1 to continue.",
	"Ever notice how fast Windows runs? Neither did I.",
	"Ever stop to think, and forget to start again?",
	"Everyone has a photographic memory. Some don't have film.",
	"Experience is something you don't get until just after you need it.",
	"Experience is what you get when you didn't get what you wanted.",
	"Few women admit their age. Few men act theirs.",
	"For every action there is an equal and opposite criticism.",
	"For Sale: Parachute. Only used once, never opened, small stain.",
	"Forget world peace. Visualize using your turn signal.",
	"Friends help you move. Real friends help you move bodies.",
	"Friends may come and go, but enemies tend to accumulate.",
	"Generally speaking, you aren't learning much when your mouth is moving.",
	"Genius does what it must, talent does what it can, and you had best do what you're told.",
	"Get a new car for your spouse; it'll be a great trade!",
	"Give a man a fish and he will eat for a day. Teach him how to fish, and he will sit in a boat and drink beer all day.",
	"Give me ambiguity or give me something else.",
	"Good judgment comes from bad experience and a lot of that comes from bad judgment.",
	"Hard work has a future payoff. Laziness pays off now.",
	"He who laughs last thinks slowest.",
	"Honk if you love peace and quiet.",
	"Honk if you want to see my finger.",
	"How do you tell when you run out of invisible ink?",
	"How does Teflon stick to the pan?",
	"How many of you believe in telekinesis? Raise my hand.",
	"I am not a vegetarian because I love animals. I am a vegetarian because I hate plants.",
	"I couldn't repair your brakes, so I made your horn louder.",
	"I didn't say it was your fault. I said I was going to blame you.",
	"I don't suffer from insanity. I enjoy every minute of it.",
	"I feel like I'm diagonally parked in a parallel universe.",
	"I get enough exercise just pushing my luck.",
	"I just got lost in thought. It was unfamiliar territory.",
	"I need someone really bad. Are you really bad?",
	"I poured Spot remover on my dog. Now he's gone.",
	"I took an IQ test and the results were negative.",
	"I tried sniffing Coke once, but the ice cubes got stuck in my nose.",
	"I used to be indecisive. Now I'm not sure.",
	"I used to have a handle on life, and then it broke.",
	"I used to have an open mind but my brains kept falling out.",
	"I won't rise to the occasion, but I'll slide over to it.",
	"I wouldn't be caught dead with a necrophiliac.",
	"I'm as confused as a baby in a topless bar.",
	"I'm not a complete idiot, some parts are missing!",
	"I'm writing a book. I've got the page numbers done.",
	"If at first you don't succeed, destroy all evidence that you tried.",
	"If at first you don't succeed, skydiving is not for you.",
	"If Barbie is so popular, why do you have to buy her friends?",
	"If ignorance is bliss, you must be orgasmic.",
	"If you can read this, I can slam on my brakes and sue you!",
	"If you can't convince them, confuse them.",
	"If you choke a smurf, what color does it turn?",
	"If you get to it and you can't do it, well there you jolly well are, aren't you.",
	"If you haven't much education you must use your brain.",
	"If you lend someone \$20, and never see that person again; it was probably worth it.",
	"If you tell the truth you don't have to remember anything.",
	"If you think nobody cares if you're alive, try missing a couple of car payments.",
	"IRS: We've got what it takes to take what you've got.",
	"It IS as bad as you think, and they ARE out to get you.",
	"It is far more impressive when others discover your good qualities without your help.",
	"It may be that your sole purpose in life is simply to serve as a warning to others.",
	"It's always darkest before dawn. So if you're going to steal the neighbor's newspaper, that's the time to do it.",
	"It's lonely at the top, but you eat better.",
	"Jack Kevorkian for White House Physician.",
	"Jesus loves you, but everyone else thinks you're an asshole.",
	"Join the Army, meet interesting people, and kill them.",
	"Keep honking. I'm reloading.",
	"Laughing stock: cattle with a sense of humor.",
	"Learn from your parents' mistakes: use birth control.",
	"Lottery: A tax on people who are bad at math.",
	"Love may be blind but marriage is a real eye-opener.",
	"Make it idiot proof and someone will make a better idiot.",
	"Monday is an awful way to spend 1/7th of your life.",
	"Montana: At least our cows are sane!",
	"More hay, Trigger? No thanks, Roy, I'm stuffed!",
	"Multitasking means screwing up several things at once.",
	"My hockey mom can beat up your soccer mom.",
	"My mind is like a steel trap, rusty and illegal in 37 states.",
	"Never ask a barber if he thinks you need a haircut.",
	"Never do card tricks for the group you play poker with.",
	"Never mess up an apology with an excuse.",
	"Never miss a good chance to shut up.",
	"Never test the depth of the water with both feet.",
	"Never underestimate the power of stupid people in large groups.",
	"No one is listening until you make a mistake.",
	"Oh Lord, give me patience, and GIVE IT TO ME NOW!",
	"Okay, who put a stop payment on my reality check?",
	"On the other hand, you have different fingers.",
	"Oops. My brain just hit a bad sector.",
	"Out of my mind. Back in five minutes.",
	"Pentiums melt in your PC, not in your hand.",
	"Plan to be spontaneous, tomorrow.",
	"Pride is what we have. Vanity is what others have.",
	"Puritanism: The haunting fear that someone, somewhere may be happy.",
	"Quantum mechanics: The dreams stuff is made of.",
	"Quickly, I must hurry, for there go my people and I am their leader.",
	"Reality is a crutch for people who can't handle drugs.",
	"Remember half the people you know are below average.",
	"Save the whales. Collect the whole set",
	"Save your breath. You'll need it to blow up your date!",
	"Sex is like air; it's not important unless you aren't getting any.",
	"Shin: a device for finding furniture in the dark.",
	"Smile, it's the second best thing you can do with your lips.",
	"Smith & Wesson: The original point and click interface.",
	"Some days you are the bug, some days you are the windshield.",
	"Some drink at the fountain of knowledge. Others just gargle.",
	"Some people are only alive because it is illegal to shoot them.",
	"Success always occurs in private and failure in full view.",
	"Suicidal twin kills sister by mistake!",
	"Support bacteria, they're the only culture some people have.",
	"The Bermuda Triangle got tired of warm weather. It moved to Finland. Now Santa Claus is missing.",
	"The colder the x-ray table, the more of your body is required on it.",
	"The early bird may get the worm, but the second mouse gets the cheese.",
	"The hardness of butter is directly proportional to the softness of the bread.",
	"The journey of a thousand miles begins with a broken fan belt and a flat tire.",
	"The more you complain, the longer God makes you live.",
	"The only substitute for good manners is fast reflexes.",
	"The problem with the gene pool is that there is no lifeguard.",
	"The quickest way to double your money is to fold it in half and put it back in your pocket.",
	"The secret of the universe is @*&^^^ NO CARRIER",
	"The severity of the itch is inversely proportional to the ability to reach it.",
	"The sex was so good that even the neighbors had a cigarette.",
	"The shortest distance between two points is under construction.",
	"The sooner you fall behind the more time you'll have to catch up.",
	"The universe is a figment of its own imagination. There's no future in time travel.",
	"There are 3 kinds of people: those who can count & those who can't.",
	"There are two theories to arguing with women. Neither one works.",
	"There's too much blood in my caffeine system.",
	"Things are more like they are now than they ever were before.",
	"Time is the best teacher; unfortunately it kills all of its students.",
	"Time is what keeps everything from happening at once.",
	"Timing has an awful lot to do with the outcome of a rain dance.",
	"To steal ideas from one person is plagiarism; to steal from many is research.",
	"To succeed in politics, it is often necessary to rise above your principles.",
	"Very funny Scotty, now beam down my clothes.",
	"Wanted: Meaningful overnight relationship.",
	"Warning: Dates in calendar are closer than they appear.",
	"We have enough youth, how about a fountain of smart?",
	"We were born naked, wet and hungry. Then things got worse.",
	"Wear short sleeves! Support your right to bare arms!",
	"What happens if you get scared half to death twice?",
	"What is a free gift? Aren't all gifts free?",
	"What's the speed of dark?",
	"When everything's coming your way, you're in the wrong lane and going the wrong way.",
	"When there's a will, I want to be in it.",
	"When you don't know what you are doing, do it neatly.",
	"Who is General Failure and why is he reading my hard disk?",
	"Who stopped payment on my reality check?",
	"Why do psychics have to ask you for your name?",
	"Why is abbreviation such a long word?",
	"Why isn't phonetic spelled the way it sounds?",
	"Women who seek to be equal to men lack ambition.",
	"You are depriving some poor village of its idiot.",
	"You can do more with a kind word and a gun than with just a kind word.",
	"You have the right to remain silent. Anything you say will be misquoted then used against you.",
	"You're just jealous because the voices are talking to me and not you!",
	"Your gene pool could use a little chlorine.",
	"Your kid may be an honors student, but you're still an idiot.",
    );

    public function onPrivmsg()
    {
        $this->processCommand($this->event->getArgument(1), true, false);
    }

    /**
     * @return void
     */
    public function onDoYow()
    {
        $source = $this->event->getSource();
        $yow = self::$yows[rand(0, count(self::$yows) - 1)];
        $this->doPrivmsg($source, $yow);
        $tw = new Phergie_Plugin_Twitter($this->client);
        $tw->twitter->sendTweet($yow);
    }
    
    public function onDoWoy()
    {
               $source = $this->event->getSource();
               $yow = self::$yows[rand(0, count(self::$yows) - 1)];
               $this->doPrivmsg($source, strrev($yow));
               $tw = new Phergie_Plugin_Twitter($this->client);
               $tw->twitter->sendTweet($yow);
    }
}
